language: objective-c
osx_image: xcode7.2
xcode_project: HHKL.xcodeproj
xcode_scheme: HHKL
xcode_sdk: iphonesimulator9.2
before_install:
       - brew update
       - brew install xctool
script:
       - carthage bootstrap --platform iOS
       - xctool -project HHKL.xcodeproj -scheme HHKL -sdk iphonesimulator9.2 -destination 'platform=iOS Simulator,name=iPhone 6s' ONLY_ACTIVE_ARCH=NO clean build
